import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Providers from "./components/Providers";

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],  // Ajoutez les weights dont vous avez besoin
  variable: '--font-raleway',  // Permet d'utiliser la police comme variable CSS
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body
          className={`${raleway.variable} font-sans antialiased`}
        >
          <Providers>
            {children}
          </Providers>
        </body>
      </html>
  );
}
